"""Type stub for the compiled `lapinbeam._core` extension (see src/py/).

Kept in sync by hand with the `#[pymethods]` in src/py/node.rs and the
functions registered in src/py/mod.rs — there is no automated stub
generation for this PyO3 extension.
"""

from typing import Any, Callable

__version__: str

class Node:
    def __init__(self, node_id: str, reconnect_interval: float | None = None) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def local_id(self) -> str: ...
    def connect_peer(self, peer_id: str) -> None: ...
    def has_peer(self, peer_id: str) -> bool: ...
    def peer_count(self) -> int: ...
    def register_actor(
        self, name: str, event_loop: Any, callback: Callable[[Any], None]
    ) -> None: ...
    def unregister_actor(self, name: str) -> None: ...
    def send_data(
        self,
        peer_id: str,
        dst_actor: str,
        payload: Any,
        reply_to: str | None = None,
        correlation_id: int | None = None,
    ) -> None: ...
    def set_event_handler(
        self, event_loop: Any, callback: Callable[[dict[str, Any]], None]
    ) -> None: ...

def encode_payload(obj: Any) -> bytes: ...
def decode_payload(data: bytes) -> Any: ...
